---
- name: Install logstash.repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo

- name: Download and install Elasticsearch Signing Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Ensure some packages are installed
  yum:
    pkg: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
  when: packages is defined
  tags:
    - install
