---
- name: Ensure all services running
  service:
    daemon_reload: yes
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ services }}"
  when: services is defined
  tags:
    - services
